name: smarthealth
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.0
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.2
  image_picker: ^1.0.7
  permission_handler: ^11.0.1
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.2
  firebase_messaging: ^15.1.3
  shared_preferences: ^2.2.2
  local_auth: ^2.3.0
  cloud_functions: ^5.6.2
  syncfusion_flutter_charts: ^31.1.19
  cached_network_image: ^3.3.0
  pdf: ^3.10.5
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  open_file: ^3.3.1
  file_picker: ^10.0.0
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/health_logo.png
    - assets/doctors-office.gif
    - assets/medical-assistant.gif
    - assets/international-nurses-day-unscreen.gif
    - assets/onboarding3.png
    - assets/login.gif
    - assets/google.png
    - assets/facebook.png
    - assets/sign-up.gif
    - assets/stethoscope.png
    - assets/kit.png
    - assets/login_illustration.png
    - assets/signup_illustration.png
    - assets/user_image.png
    - assets/fruits.png
    - assets/covid19.png
    - assets/doctor.png
    - assets/doctor_icon.png
    - assets/Caduceus.jpg

